import React, { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

const factors = [
  { label: "Air Quality Index", value: 85, color: "#16a34a" },
  { label: "Wind Direction Safety", value: 72, color: "#3b82f6" },
  { label: "Temperature Threshold", value: 91, color: "#D4AF37" },
  { label: "Regulatory Compliance", value: 95, color: "#8b5cf6" },
];

export default function ProductionSection() {
  const gaugeRef = useRef(null);
  const sectionRef = useRef(null);
  const probability = 87;

  useEffect(() => {
    const circumference = 2 * Math.PI * 100;
    const circle = gaugeRef.current;
    if (!circle) return;

    gsap.fromTo(circle,
      { strokeDashoffset: circumference },
      {
        strokeDashoffset: circumference - (probability / 100) * circumference,
        duration: 2, ease: "power2.out",
        scrollTrigger: { trigger: sectionRef.current, start: "top 70%" }
      }
    );

    // Animate factor bars
    sectionRef.current.querySelectorAll(".l-factor-fill").forEach((bar, i) => {
      gsap.fromTo(bar, { width: "0%" }, {
        width: `${factors[i].value}%`, duration: 1.2, delay: i * 0.15,
        ease: "power2.out",
        scrollTrigger: { trigger: bar, start: "top 90%" }
      });
    });
  }, []);

  const circumference = 2 * Math.PI * 100;
  const isContinue = probability >= 60;

  return (
    <section className="l-section" id="production" ref={sectionRef}>
      <div className="l-container">
        <div className="l-section-title">
          <div className="l-badge">🏭 Production Status</div>
          <h2>OCP Production Probability</h2>
          <p>AI-driven assessment of production continuation based on environmental factors</p>
        </div>

        <div className="l-prod-gauge-wrapper">
          <div className="l-prod-gauge">
            <svg width="240" height="240" viewBox="0 0 240 240">
              <circle cx="120" cy="120" r="100" stroke="var(--bg-tertiary)" strokeWidth="12" fill="none" />
              <circle ref={gaugeRef} cx="120" cy="120" r="100"
                stroke={isContinue ? "#16a34a" : "#ef4444"} strokeWidth="12" fill="none"
                strokeDasharray={circumference} strokeDashoffset={circumference}
                strokeLinecap="round"
                style={{ filter: `drop-shadow(0 0 12px ${isContinue ? "rgba(22,163,74,0.4)" : "rgba(239,68,68,0.4)"})` }}
              />
            </svg>
            <div className="l-prod-gauge-text">
              <div className="l-prod-gauge-value">{probability}%</div>
              <div className="l-prod-gauge-label">Probability</div>
            </div>
          </div>

          <div className={`l-prod-status ${isContinue ? "continue" : "stop"}`}>
            {isContinue ? "🟢" : "🔴"} {isContinue ? "Continue Production" : "Stop Recommended"}
          </div>
        </div>

        <div className="l-prod-factors">
          {factors.map((f, i) => (
            <div key={i} className="l-glass l-factor-card">
              <div className="l-factor-label">
                <span>{f.label}</span>
                <span style={{ color: f.color, fontWeight: 700 }}>{f.value}%</span>
              </div>
              <div className="l-factor-bar">
                <div className="l-factor-fill" style={{ background: f.color, width: 0 }} />
              </div>
            </div>
          ))}
        </div>

        <p style={{ textAlign: "center", marginTop: "2rem", fontSize: "0.88rem", color: "var(--text-muted)", maxWidth: 600, marginLeft: "auto", marginRight: "auto" }}>
          Predictions are generated by our XGBoost machine learning model analyzing wind patterns,
          air quality indices, temperature, and regulatory thresholds in real-time.
        </p>
      </div>
    </section>
  );
}
